### ISSUE TITLE
fullchain.pem is chain.pem + cert.pem, should be cert.pem + chain.pem

### ISSUE THREAD

**Issue by rogerbraun** [zealot128/ruby-letsencrypt-cli#1]
Using the generated fullchain.pem, nginx gives the following error:

`2015/12/06 22:05:36 [emerg] 18678#0: SSL_CTX_use_PrivateKey_file("/home/letsencrypt/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

Looking into the fullchain.pem, it contains the chain.pem followed by the cert.pem. According to http://nginx.org/en/docs/http/configuring_https_servers.html, the full chain needs to be the cert.pem followed by the chain.pem.

Regenerating the fullchain.pem in the correct order manually (`cat cert.pem chain.pem > fullchain.pem`) resovles the error.

Thanks for the gem!

**Comment by unixcharles** [comment]
Fixed upstream in https://github.com/unixcharles/acme-client/issues/2.

@zealot128 I'll release a new gem version tomorrow.

**Comment by zealot128** [comment]
Thx! I've bumped the gem dependency version accordingly in 7d038cb5ec6a0ef792de21bf3a7603fa68ebd7a5
