### ISSUE TITLE
Manage command exited automatically if any host is valid

### ISSUE THREAD

**Issue by ryudoawaru** [zealot128/ruby-letsencrypt-cli#16]
``` bash
 letsencrypt-cli manage --days-valid 30 --account-key /root/account_key.pem --key-directory /etc/letsencrypt/live --webroot-path /var/www/acme-challenge example1.com example2.com
2016-10-17 15:27:47 +0800: Certificate '/etc/letsencrypt/live/example1.com/cert.pem' valid until 2016-12-27.
```

In my command I input 2 host but it exited automatically when the first one is valid.

Able to happen in newest version (0.4.1)

**Comment by ondrejbima** [comment]
It's correct, ONE certificated for two hostnames.
If you want two separated certificate you have to run commnd twice for each hostname.
You can have up 100 hostnames in one certificate on LE.

**Comment by ryudoawaru** [comment]
Got it, thank you
