### ISSUE TITLE
Certificate not regenerated when domains are added/removed

### ISSUE THREAD

**Issue by mickael9** [zealot128/ruby-letsencrypt-cli#7]
With the `cert` or `manage` commands, providing new domains or removing some will not regenerate a new certificate if the current one is not expired. Perhaps an option could be added to force regeneration if the provided domains don't strictly match the current certificate ?

An option to unconditionally regenerate could also be useful.

**Comment by duderamos** [comment]
Or maybe we could revoke current one. Is there a date to get it in a new release @zealot128 ?

**Comment by zealot128** [comment]
I've pushed some code that should handle the added case. I havn't tested it thoroughly, as I have no use case atm and not too much time. Feel free to try version 0.3.0 on Rubygems and report if that fixes your issue!
